/* Generated By:JJTree: Do not edit this line. ASTAnnotationValueValueArrayInitializer.java */

package kiev.parser;

import kiev.Kiev;
import kiev.stdlib.*;
import kiev.vlang.*;

/**
 * @author Maxim Kizub
 *
 */

@node
public class ASTAnnotationValueValueArrayInitializer extends SimpleNode {
	
	@att public final NArr<ASTNode> values;

	public void jjtAddChild(ASTNode n, int i) {
		values.append(n);
	}

}
