/* Generated By:JJTree: Do not edit this line. ASTFieldDecl.java */

/*
 Copyright (C) 1997-1998, Forestro, http://forestro.com

 This file is part of the Kiev compiler.
 
 The Kiev compiler is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation.

 The Kiev compiler is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the Kiev compiler; see the file License.  If not, write to
 the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 Boston, MA 02111-1307, USA.
*/
  
package kiev.parser;

import kiev.Kiev;
import kiev.stdlib.*;
import kiev.vlang.*;

/**
 * $Header: /home/CVSROOT/forestro/kiev/kiev/parser/Attic/ASTFieldDecl.java,v 1.1.2.1 1999/05/29 21:03:06 max Exp $
 * @author Maxim Kizub
 * @version $Revision: 1.1.2.1 $
 *
 */

@node
public class ASTFieldDecl extends ASTNode {

	@att public ASTModifiers			modifiers;
	@att public ASTType					type;
    @att public ASTIdentifier			name;
    @att public Expr					init;
	public int							dim;
    public boolean						of_wrapper;

	public void jjtAddChild(ASTNode n, int i) {
		if (init == null)
			init=(Expr)n;
		else
			throw new CompilerException(n.getPos(),"Bad child number "+i+": "+n);
    }

	public ASTNode resolve(Type reqType) {
		return null;
	}
    
	public Dumper toJava(Dumper dmp) {
		modifiers.toJava(dmp);
		type.toJava(dmp).space();
    	dmp.append(name);
        for(int i=0; i < dim; i++) dmp.append("[]");
        if( init != null ) {
        	dmp.space().append('=').space().append(init);
        }
        return dmp;
    }
}
