/* Generated By:JJTree: Do not edit this line. ASTRuleIstheExpression.java */

/*
 Copyright (C) 1997-1998, Forestro, http://forestro.com

 This file is part of the Kiev compiler.

 The Kiev compiler is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation.

 The Kiev compiler is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the Kiev compiler; see the file License.  If not, write to
 the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 Boston, MA 02111-1307, USA.
*/

package kiev.parser;

import kiev.Kiev;
import kiev.stdlib.*;
import kiev.vlang.*;

/**
 * $Header: /home/CVSROOT/forestro/kiev/kiev/parser/ASTRuleIstheExpression.java,v 1.3.4.1 1999/02/15 21:45:09 max Exp $
 * @author Maxim Kizub
 * @version $Revision: 1.3.4.1 $
 *
 */

public class ASTRuleIstheExpression extends ASTRuleNode {

	public ASTIdentifier	name;
	public Expr				expr;

	public ASTRuleIstheExpression(int id) {
		super(0);
	}

	public void jjtAddChild(ASTNode n, int i) {
    	switch(i) {
        case 0: name=(ASTIdentifier)n; setPos(name.getPos()); break;
        case 1: expr=(Expr)n; break;
        default: throw new CompilerException(n.getPos(),"Bad child number "+i+": "+n);
        }
    }

    public ASTNode resolve(Type reqType) {
		PVar<ASTNode> v = new PVar<ASTNode>();
		if( !PassInfo.resolveNameR(v,null,name.name,null,0) )
			throw new CompilerException(pos,"Unresolved identifier "+name.name);
		if( !(v instanceof Var) )
    		throw new CompilerException(name.getPos(),"Identifier is not a var");
    	return new RuleIstheExpr(getPos(), (Var)v, expr.resolveExpr(((Var)v).type.args[0]));
    }

	public void	createText(StringBuffer sb) { throw new CompilerException(name.getPos(),"Internal error"); }
	public void	resolve1(JumpNodes jn) { throw new CompilerException(name.getPos(),"Internal error"); }

}
