/* Generated By:JJTree: Do not edit this line. ASTTryStatement.java */

/*
 Copyright (C) 1997-1998, Forestro, http://forestro.com

 This file is part of the Kiev compiler.
 
 The Kiev compiler is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation.

 The Kiev compiler is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the Kiev compiler; see the file License.  If not, write to
 the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 Boston, MA 02111-1307, USA.
*/
  
package kiev.parser;

import kiev.Kiev;
import kiev.vlang.*;
import kiev.stdlib.*;
import kiev.tree.*;

import static kiev.stdlib.Debug.*;
import syntax kiev.Syntax;

/**
 * $Header: /home/CVSROOT/forestro/kiev/kiev/parser/ASTTryStatement.java,v 1.3 1998/10/26 23:47:05 max Exp $
 * @author Maxim Kizub
 * @version $Revision: 1.3 $
 *
 */

public class ASTTryStatement extends ASTStatement {
	public ASTStatement		body;
    public ASTCatchInfo∏	catchers;
    public ASTFinallyInfo	finally_catcher;
    
	public ASTTryStatement(int id) {
		super(kiev.Kiev.k.getToken(0)==null?0:kiev.Kiev.k.getToken(0).getPos());
		catchers = new ASTCatchInfo∏(this);
	}

	public void jjtAddChild(ASTNode n, int i) {
    	if(i==0) {
			body=(ASTStatement)n;
		} else {
        	if( n instanceof ASTCatchInfo )
	        	catchers.append((ASTCatchInfo)n);
            else if( n instanceof ASTFinallyInfo )
            	finally_catcher = (ASTFinallyInfo)n;
        }
    }

	public Node resolve(Type reqType) {
//		PassInfo.push(this);
//        try {
//			try {
//				body = (Statement)body.resolve(Type.tpVoid);
//			} catch(Exception e ) { Kiev.reportError(body.pos,e); }
//            for(int i=0; i < catchers.length; i++) {
//				try {
//					catchers[i] = ((ASTCatchInfo)catchers[i]).resolve(Type.tpVoid);
//				} catch(Exception e ) {
//					Kiev.reportError(catchers[i].pos,e);
//				}
//			}
//			try {
//            	if( finally_catcher != null )
//					finally_catcher = ((ASTFinallyInfo)finally_catcher).resolve(Type.tpVoid);
//			} catch(Exception e ) {
//				Kiev.reportError(pos,e);
//			}
//		} finally { PassInfo.pop(this); }
		return new TryStat(pos,parent,body,catchers,finally_catcher).resolve(reqType);
	}

	public Dumper toJava(Dumper dmp) {
		dmp.append("try").space().append(body).newLine();
		for(int i=0; i < catchers.length; i++)
			dmp.append(catchers[i]).newLine();
		if(finally_catcher != null)
			dmp.append(finally_catcher).newLine();
		return dmp;
	}

}
