/* Generated By:JJTree: Do not edit this line. ASTType.java */

/*
 Copyright (C) 1997-1998, Forestro, http://forestro.com

 This file is part of the Kiev compiler.
 
 The Kiev compiler is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation.

 The Kiev compiler is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the Kiev compiler; see the file License.  If not, write to
 the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 Boston, MA 02111-1307, USA.
*/
  
package kiev.parser;

import kiev.Kiev;
import kiev.stdlib.*;
import kiev.vlang.*;

/**
 * $Header: /home/CVSROOT/forestro/kiev/kiev/parser/ASTType.java,v 1.3 1998/10/26 23:47:06 max Exp $
 * @author Maxim Kizub
 * @version $Revision: 1.3 $
 *
 */

@node
public class ASTType extends ASTNode {

	public static ASTType[]	emptyArray = new ASTType[0];

	public int				dim;
    @att public ASTNode		asttype;
	
	@ref private Type		type;
	
	ASTType() {
	}

	ASTType(int id) {
	}

	ASTType(int pos, int dim, ASTNode asttype) {
		super(pos);
		this.dim = dim;
		this.asttype = asttype;
	}

	ASTType(int pos, Type type) {
		super(pos);
		this.type = type;
	}

	public void jjtAddChild(ASTNode n, int i) {
		if( i==0 ) {
			asttype = n;
            pos = n.getPos();
		}
        else {
			throw new CompilerException(n.getPos(),"Bad child number "+i+": "+n);
        }
    }
    
	public Type getType() {
		if( type != null )
			return type;
		Type tp = Type.tpVoid;
		if( asttype instanceof ASTNonArrayType ) {
			try {
				type = tp = ((ASTNonArrayType)asttype).getType();
				for(int i=0; i < dim; i++)
					type = tp = Type.newArrayType(tp);
			} catch(Exception e ) {
				Kiev.reportError(asttype.getPos(),e);
			}
		}
		else if( asttype instanceof ASTClosureType ) {
			type = tp = ((ASTClosureType)asttype).getType();
		} else {
			throw new CompilerException(asttype.getPos(),"Bad type node "+asttype);
		}
		return tp;
	}
	
	public String toString() {
		String s;
		if (type != null)
			s = type.toString();
		else
			s = asttype.toString();
    	for(int i=0; i < dim; i++) s += "[]";
        return s;
	}

	public Dumper toJava(Dumper dmp) {
		if (type != null)
			type.toJava(dmp);
		else
			asttype.toJava(dmp);
    	for(int i=0; i < dim; i++) dmp.append("[]");
        return dmp.space();
	}
}

