/* Generated By:JJTree: Do not edit this line. ASTVarDecls.java */

/*
 Copyright (C) 1997-1998, Forestro, http://forestro.com

 This file is part of the Kiev compiler.

 The Kiev compiler is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation.

 The Kiev compiler is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with the Kiev compiler; see the file License.  If not, write to
 the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 Boston, MA 02111-1307, USA.
*/

package kiev.parser;

import kiev.Kiev;
import kiev.stdlib.*;
import kiev.vlang.*;

/**
 * $Header: /home/CVSROOT/forestro/kiev/kiev/parser/ASTVarDecls.java,v 1.3.4.1 1999/02/17 21:38:29 max Exp $
 * @author Maxim Kizub
 * @version $Revision: 1.3.4.1 $
 *
 */

@node
public class ASTVarDecls extends ASTNode {
	@att public ASTModifiers			modifiers;
	@att public ASTType					type;
	@att public final NArr<ASTVarDecl>	vars;

	public ASTVarDecls() {
		vars = new NArr<ASTVarDecl>(this, new AttrSlot("vars", true, true));
	}

	public ASTVarDecls(int id) {
		this();
	}

	public void jjtAddChild(ASTNode n, int i) {
		if( n instanceof ASTModifiers) {
			modifiers = (ASTModifiers)n;
		}
        else if( n instanceof ASTType ) {
			type = (ASTType)n;
		}
        else if( n instanceof ASTVarDecl ) {
			if( vars.length == 0 ) pos = n.pos;
			vars.append((ASTVarDecl)n);
		}
        else {
			throw new CompilerException(n.getPos(),"Bad child number "+i+": "+n);
        }
    }

    public boolean hasFinal() {
		foreach (ASTModifier m; modifiers.modifier)
			if (m.flag() == ACC_FINAL) return true;
		return false;
    }

    public boolean hasForward() {
		foreach (ASTModifier m; modifiers.modifier)
			if (m.flag() == ACC_FORWARD) return true;
		return false;
    }

	public Dumper toJava(Dumper dmp) {
        	modifiers.toJava(dmp);
		type.toJava(dmp).space();
		for(int i=0; i < vars.length; i++) {
			vars[i].toJava(dmp);
            if( i < vars.length - 1 ) dmp.append(',').space();
        }
		return dmp;
	}
}

