/* Generated By:JJTree: Do not edit this line. kiev020TreeConstants.java */

package kiev.parser;

public interface kiev020TreeConstants
{
  public int JJTFILEUNIT = 0;
  public int JJTPACKAGE = 1;
  public int JJTPRAGMA = 2;
  public int JJTIMPORT = 3;
  public int JJTTYPEDEF = 4;
  public int JJTOPDEF = 5;
  public int JJTSYNTAXDECLARATION = 6;
  public int JJTTYPEDECLARATION = 7;
  public int JJTVOID = 8;
  public int JJTENUMDECLARATION = 9;
  public int JJTCASETYPEDECLARATION = 10;
  public int JJTEXTENDS = 11;
  public int JJTIMPLEMENTS = 12;
  public int JJTGENERATE = 13;
  public int JJTARGUMENTDECLARATION = 14;
  public int JJTMODIFIER = 15;
  public int JJTPACK = 16;
  public int JJTACCESS = 17;
  public int JJTFIELDDECL = 18;
  public int JJTVARDECLS = 19;
  public int JJTVARDECL = 20;
  public int JJTNEWINITIALIZEDARRAYEXPRESSION = 21;
  public int JJTFORMALPARAMETER = 22;
  public int JJTTHROWS = 23;
  public int JJTIDENTIFIERALIAS = 24;
  public int JJTOPERATORALIAS = 25;
  public int JJTMETHODDECLARATION = 26;
  public int JJTREQUAREDECLARATION = 27;
  public int JJTENSUREDECLARATION = 28;
  public int JJTINVARIANTDECLARATION = 29;
  public int JJTRULEDECLARATION = 30;
  public int JJTINITIALIZER = 31;
  public int JJTTYPE = 32;
  public int JJTCLOSURETYPE = 33;
  public int JJTNONARRAYTYPE = 34;
  public int JJTPRIMITIVETYPE = 35;
  public int JJTIDENTIFIER = 36;
  public int JJTQNAME = 37;
  public int JJTCOMMAEXPRESSION = 38;
  public int JJTRULEOREXPRESSION = 39;
  public int JJTRULEANDEXPRESSION = 40;
  public int JJTRULEEXPRESSION = 41;
  public int JJTRULEISTHEEXPRESSION = 42;
  public int JJTRULEISONEOFEXPRESSION = 43;
  public int JJTRULECUTEXPRESSION = 44;
  public int JJTOPERATOR = 45;
  public int JJTCASTOPERATOR = 46;
  public int JJTEXPRESSION = 47;
  public int JJTREPARSEEXPRESSION = 48;
  public int JJTCALLEXPRESSION = 49;
  public int JJTTYPECLASSEXPRESSION = 50;
  public int JJTCALLACCESSEXPRESSION = 51;
  public int JJTACCESSEXPRESSION = 52;
  public int JJTARRAYELEMENTACCESSEXPRESSION = 53;
  public int JJTNEWACCESSEXPRESSION = 54;
  public int JJTANONYMOUSECLOSURE = 55;
  public int JJTCONSTEXPRESSION = 56;
  public int JJTNEWEXPRESSION = 57;
  public int JJTNEWARRAYEXPRESSION = 58;
  public int JJTREPARSESTATEMENT = 59;
  public int JJTLABELEDSTATEMENT = 60;
  public int JJTBLOCK = 61;
  public int JJTRULEBLOCK = 62;
  public int JJTCONDBLOCK = 63;
  public int JJTCONDSTATEMENT = 64;
  public int JJTEMPTYSTATEMENT = 65;
  public int JJTSTATEMENTEXPRESSION = 66;
  public int JJTSWITCHSTATEMENT = 67;
  public int JJTNORMALCASE = 68;
  public int JJTPIZZACASE = 69;
  public int JJTIFSTATEMENT = 70;
  public int JJTWHILESTATEMENT = 71;
  public int JJTDOSTATEMENT = 72;
  public int JJTFORSTATEMENT = 73;
  public int JJTFOREACHSTATEMENT = 74;
  public int JJTGOTOSTATEMENT = 75;
  public int JJTBREAKSTATEMENT = 76;
  public int JJTCONTINUESTATEMENT = 77;
  public int JJTRETURNSTATEMENT = 78;
  public int JJTTHROWSTATEMENT = 79;
  public int JJTSYNCHRONIZEDSTATEMENT = 80;
  public int JJTWITHSTATEMENT = 81;
  public int JJTTRYSTATEMENT = 82;
  public int JJTCATCHINFO = 83;
  public int JJTFINALLYINFO = 84;


  public String[] jjtNodeName = {
    "FileUnit",
    "Package",
    "Pragma",
    "Import",
    "Typedef",
    "Opdef",
    "SyntaxDeclaration",
    "TypeDeclaration",
    "void",
    "EnumDeclaration",
    "CaseTypeDeclaration",
    "Extends",
    "Implements",
    "Generate",
    "ArgumentDeclaration",
    "Modifier",
    "Pack",
    "Access",
    "FieldDecl",
    "VarDecls",
    "VarDecl",
    "NewInitializedArrayExpression",
    "FormalParameter",
    "Throws",
    "IdentifierAlias",
    "OperatorAlias",
    "MethodDeclaration",
    "RequareDeclaration",
    "EnsureDeclaration",
    "InvariantDeclaration",
    "RuleDeclaration",
    "Initializer",
    "Type",
    "ClosureType",
    "NonArrayType",
    "PrimitiveType",
    "Identifier",
    "QName",
    "CommaExpression",
    "RuleOrExpression",
    "RuleAndExpression",
    "RuleExpression",
    "RuleIstheExpression",
    "RuleIsoneofExpression",
    "RuleCutExpression",
    "Operator",
    "CastOperator",
    "Expression",
    "ReparseExpression",
    "CallExpression",
    "TypeClassExpression",
    "CallAccessExpression",
    "AccessExpression",
    "ArrayElementAccessExpression",
    "NewAccessExpression",
    "AnonymouseClosure",
    "ConstExpression",
    "NewExpression",
    "NewArrayExpression",
    "ReparseStatement",
    "LabeledStatement",
    "Block",
    "RuleBlock",
    "CondBlock",
    "CondStatement",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "NormalCase",
    "PizzaCase",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForEachStatement",
    "GotoStatement",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "WithStatement",
    "TryStatement",
    "CatchInfo",
    "FinallyInfo",
  };
}
