/* Generated By:JavaCC: Do not edit this line. kiev040Constants.java */
package kiev.parser;

public interface kiev040Constants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 11;
  int FORMAL_COMMENT = 12;
  int MULTI_LINE_COMMENT = 13;
  int ABSTRACT = 15;
  int BOOLEAN = 16;
  int BREAK = 17;
  int BYTE = 18;
  int CASE = 19;
  int CATCH = 20;
  int CHAR = 21;
  int CLASS = 22;
  int CONTINUE = 23;
  int _DEFAULT = 24;
  int DO = 25;
  int DOUBLE = 26;
  int ELSE = 27;
  int EXTENDS = 28;
  int FALSE = 29;
  int FINAL = 30;
  int FINALLY = 31;
  int FLOAT = 32;
  int FOR = 33;
  int FOREACH = 34;
  int GOTO = 35;
  int IF = 36;
  int IMPLEMENTS = 37;
  int IMPORT = 38;
  int INT = 39;
  int INTERFACE = 40;
  int LONG = 41;
  int NATIVE = 42;
  int NEW = 43;
  int NULL = 44;
  int PACKAGE = 45;
  int RETURN = 46;
  int SHORT = 47;
  int STATIC = 48;
  int SWITCH = 49;
  int SYNCHRONIZED = 50;
  int WITH = 51;
  int THROW = 52;
  int THROWS = 53;
  int TRANSIENT = 54;
  int TRUE = 55;
  int TRY = 56;
  int VOID = 57;
  int VOLATILE = 58;
  int VIEW = 59;
  int WHILE = 60;
  int ARROW = 61;
  int FUNCTION = 62;
  int VARARGS = 63;
  int RULE = 64;
  int PCUT = 65;
  int CAST = 66;
  int REINTERP = 67;
  int ALIAS = 68;
  int OPERATOR_ID = 69;
  int TYPEDEF = 70;
  int ENUM = 71;
  int REQUIRE = 72;
  int ENSURE = 73;
  int INVARIANT = 74;
  int META_INTERFACE = 75;
  int META_SINGLETON = 76;
  int META_FORWARD = 77;
  int META_UNERASABLE = 78;
  int META_VIRTUAL = 79;
  int META_PACKED = 80;
  int META_STATIC = 81;
  int META_ABSTRACT = 82;
  int META_FINAL = 83;
  int META_NATIVE = 84;
  int META_SYNCHRONIZED = 85;
  int META_TRANSIENT = 86;
  int META_VOLATILE = 87;
  int META_THROWS = 88;
  int META_ACCESS1 = 89;
  int META_PUBLIC = 90;
  int PUBLIC = 91;
  int META_PROTECTED = 92;
  int PROTECTED = 93;
  int META_PRIVATE = 94;
  int PRIVATE = 95;
  int READ_ONLY = 96;
  int WRITE_ONLY = 97;
  int READ_WRITE = 98;
  int NO_READ_WRITE = 99;
  int COMMA1 = 100;
  int COLON1 = 101;
  int OPEN_ACCESS = 102;
  int CLOSE_ACCESS = 103;
  int PRAGMA = 109;
  int PRAGMA_ENABLE = 110;
  int PRAGMA_DISABLE = 111;
  int INTEGER_LITERAL = 112;
  int LONG_INTEGER_LITERAL = 113;
  int DECIMAL_LITERAL = 114;
  int HEX_LITERAL = 115;
  int OCTAL_LITERAL = 116;
  int FLOATING_POINT_LITERAL = 117;
  int DOUBLE_POINT_LITERAL = 118;
  int EXPONENT = 119;
  int REPARSE_EXPRESSION = 120;
  int REPARSE_STATEMENT = 121;
  int REPARSE_TYPE = 122;
  int CHARACTER_LITERAL = 123;
  int STRING_LITERAL = 124;
  int IDENTIFIER = 125;
  int LETTER = 126;
  int DIGIT = 127;
  int ID_STRING_LITERAL = 128;
  int LPAREN = 129;
  int RPAREN = 130;
  int LBRACE = 131;
  int RBRACE = 132;
  int LBRACKET = 133;
  int RBRACKET = 134;
  int SEMICOLON = 135;
  int COMMA = 136;
  int DOT = 137;
  int COLON = 138;
  int QUESTION = 139;
  int LT = 140;
  int GT = 141;
  int ASSIGN = 142;
  int ASSIGN2 = 143;
  int BANG = 144;
  int TILDE = 145;
  int EQ = 146;
  int LE = 147;
  int GE = 148;
  int NE = 149;
  int SC_OR = 150;
  int SC_AND = 151;
  int INCR = 152;
  int DECR = 153;
  int PLUS = 154;
  int MINUS = 155;
  int STAR = 156;
  int SLASH = 157;
  int BIT_AND = 158;
  int BIT_OR = 159;
  int XOR = 160;
  int REM = 161;
  int LSHIFT = 162;
  int PLUSASSIGN = 163;
  int MINUSASSIGN = 164;
  int STARASSIGN = 165;
  int SLASHASSIGN = 166;
  int ANDASSIGN = 167;
  int ORASSIGN = 168;
  int XORASSIGN = 169;
  int REMASSIGN = 170;
  int LSHIFTASSIGN = 171;
  int RSIGNEDSHIFTASSIGN = 172;
  int RUNSIGNEDSHIFTASSIGN = 173;
  int IS_THE = 174;
  int IS_ONE_OF = 175;
  int OPERATOR_AT = 176;
  int OPERATOR_SHARP = 177;
  int OPERATOR_LRBRACKETS = 178;
  int OPERATOR_UPPER_BOUND = 179;
  int OPERATOR_LOWER_BOUND = 180;
  int OPERATOR = 181;

  int DEFAULT = 0;
  int IN_PRAGMA = 1;
  int IN_SINGLE_LINE_COMMENT = 2;
  int IN_FORMAL_COMMENT = 3;
  int IN_MULTI_LINE_COMMENT = 4;
  int IN_ACCESS = 5;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*{\"",
    "\"}*/\"",
    "\"//\"",
    "<token of kind 9>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 14>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"with\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"view\"",
    "\"while\"",
    "\"->\"",
    "\"fun\"",
    "\"...\"",
    "\"rule\"",
    "\"$cut\"",
    "\"$cast\"",
    "\"$reinterp\"",
    "\"alias\"",
    "\"operator\"",
    "\"typedef\"",
    "\"enum\"",
    "\"require\"",
    "\"ensure\"",
    "\"invariant\"",
    "\"@interface\"",
    "\"@singleton\"",
    "\"@forward\"",
    "\"@unerasable\"",
    "\"@virtual\"",
    "\"@packed\"",
    "\"@static\"",
    "\"@abstract\"",
    "\"@final\"",
    "\"@native\"",
    "\"@synchronized\"",
    "\"@transient\"",
    "\"@volatile\"",
    "\"@throws\"",
    "\"@access\"",
    "\"@public\"",
    "\"public\"",
    "\"@protected\"",
    "\"protected\"",
    "\"@private\"",
    "\"private\"",
    "<READ_ONLY>",
    "<WRITE_ONLY>",
    "\"rw\"",
    "<NO_READ_WRITE>",
    "\",\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"pragma\"",
    "\"enable\"",
    "\"disable\"",
    "<INTEGER_LITERAL>",
    "<LONG_INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DOUBLE_POINT_LITERAL>",
    "<EXPONENT>",
    "<REPARSE_EXPRESSION>",
    "<REPARSE_STATEMENT>",
    "<REPARSE_TYPE>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<ID_STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"?\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\":=\"",
    "\"!\"",
    "\"~\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"?=\"",
    "\"@=\"",
    "\"@\"",
    "\"#\"",
    "<OPERATOR_LRBRACKETS>",
    "\"\\u2264\"",
    "\"\\u2265\"",
    "<OPERATOR>",
  };

}
