/* Generated By:JavaCC: Do not edit this line. kiev040Constants.java */
/*******************************************************************************
 * Copyright (c) 2005-2007 UAB "MAKSINETA".
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Common Public License Version 1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     "Maxim Kizub" mkizub@symade.com - initial design and implementation
 *******************************************************************************/
package kiev.parser;

public interface kiev040Constants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 11;
  int FORMAL_COMMENT = 12;
  int MULTI_LINE_COMMENT = 13;
  int ABSTRACT = 15;
  int ANY = 16;
  int BOOLEAN = 17;
  int BREAK = 18;
  int BYTE = 19;
  int CASE = 20;
  int CATCH = 21;
  int CHAR = 22;
  int CLASS = 23;
  int CONTINUE = 24;
  int _DEFAULT = 25;
  int DO = 26;
  int DOUBLE = 27;
  int ELSE = 28;
  int EXTENDS = 29;
  int FALSE = 30;
  int FINAL = 31;
  int FINALLY = 32;
  int FLOAT = 33;
  int FOR = 34;
  int FOREACH = 35;
  int GOTO = 36;
  int IF = 37;
  int IF_REWR = 38;
  int IMPLEMENTS = 39;
  int IMPORT = 40;
  int INT = 41;
  int INTERFACE = 42;
  int METATYPE = 43;
  int LONG = 44;
  int NATIVE = 45;
  int NEW = 46;
  int NULL = 47;
  int PACKAGE = 48;
  int RETURN = 49;
  int SHORT = 50;
  int STATIC = 51;
  int SWITCH = 52;
  int SYNCHRONIZED = 53;
  int WITH = 54;
  int THROW = 55;
  int THROWS = 56;
  int TRANSIENT = 57;
  int TRUE = 58;
  int TRY = 59;
  int VOID = 60;
  int VOLATILE = 61;
  int VIEW = 62;
  int WHILE = 63;
  int ARROW = 64;
  int FUNCTION = 65;
  int VARARGS = 66;
  int RULE = 67;
  int PCUT = 68;
  int CAST = 69;
  int REINTERP = 70;
  int ALIAS = 71;
  int OPERATOR_ID = 72;
  int TYPEDEF = 73;
  int ENUM = 74;
  int REQUIRE = 75;
  int ENSURE = 76;
  int INVARIANT = 77;
  int META_INTERFACE = 78;
  int META_SINGLETON = 79;
  int META_FORWARD = 80;
  int META_UNERASABLE = 81;
  int META_VIRTUAL = 82;
  int META_PACKED = 83;
  int META_MACRO = 84;
  int META_STATIC = 85;
  int META_ABSTRACT = 86;
  int META_FINAL = 87;
  int META_NATIVE = 88;
  int META_SYNCHRONIZED = 89;
  int META_TRANSIENT = 90;
  int META_VOLATILE = 91;
  int META_THROWS = 92;
  int META_ACCESS1 = 93;
  int META_PUBLIC = 94;
  int PUBLIC = 95;
  int META_PROTECTED = 96;
  int PROTECTED = 97;
  int META_PRIVATE = 98;
  int PRIVATE = 99;
  int READ_ONLY = 100;
  int WRITE_ONLY = 101;
  int READ_WRITE = 102;
  int NO_READ_WRITE = 103;
  int COMMA1 = 104;
  int COLON1 = 105;
  int OPEN_ACCESS = 106;
  int CLOSE_ACCESS = 107;
  int PRAGMA = 113;
  int PRAGMA_ENABLE = 114;
  int PRAGMA_DISABLE = 115;
  int INTEGER_LITERAL = 116;
  int LONG_INTEGER_LITERAL = 117;
  int DECIMAL_LITERAL = 118;
  int HEX_LITERAL = 119;
  int OCTAL_LITERAL = 120;
  int FLOATING_POINT_LITERAL = 121;
  int DOUBLE_POINT_LITERAL = 122;
  int EXPONENT = 123;
  int REPARSE_EXPRESSION = 124;
  int REPARSE_STATEMENT = 125;
  int REPARSE_TYPE = 126;
  int CHARACTER_LITERAL = 127;
  int STRING_LITERAL = 128;
  int IDENTIFIER = 129;
  int LETTER = 130;
  int DIGIT = 131;
  int ID_STRING_LITERAL = 132;
  int LPAREN = 133;
  int RPAREN = 134;
  int LBRACE = 135;
  int RBRACE = 136;
  int LBRACKET = 137;
  int RBRACKET = 138;
  int SEMICOLON = 139;
  int COMMA = 140;
  int DOT = 141;
  int COLON = 142;
  int QUESTION = 143;
  int LT = 144;
  int GT = 145;
  int ASSIGN = 146;
  int ASSIGN2 = 147;
  int BANG = 148;
  int TILDE = 149;
  int EQ = 150;
  int LE = 151;
  int GE = 152;
  int NE = 153;
  int SC_OR = 154;
  int SC_AND = 155;
  int INCR = 156;
  int DECR = 157;
  int PLUS = 158;
  int MINUS = 159;
  int STAR = 160;
  int SLASH = 161;
  int BIT_AND = 162;
  int BIT_OR = 163;
  int XOR = 164;
  int REM = 165;
  int LSHIFT = 166;
  int PLUSASSIGN = 167;
  int MINUSASSIGN = 168;
  int STARASSIGN = 169;
  int SLASHASSIGN = 170;
  int ANDASSIGN = 171;
  int ORASSIGN = 172;
  int XORASSIGN = 173;
  int REMASSIGN = 174;
  int LSHIFTASSIGN = 175;
  int RSIGNEDSHIFTASSIGN = 176;
  int RUNSIGNEDSHIFTASSIGN = 177;
  int IS_THE = 178;
  int IS_ONE_OF = 179;
  int OPERATOR_AT = 180;
  int OPERATOR_SHARP = 181;
  int OPERATOR_LRBRACKETS = 182;
  int OPERATOR_UPPER_BOUND = 183;
  int OPERATOR_LOWER_BOUND = 184;
  int OPERATOR = 185;

  int DEFAULT = 0;
  int IN_PRAGMA = 1;
  int IN_SINGLE_LINE_COMMENT = 2;
  int IN_FORMAL_COMMENT = 3;
  int IN_MULTI_LINE_COMMENT = 4;
  int IN_ACCESS = 5;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*{\"",
    "\"}*/\"",
    "\"//\"",
    "<token of kind 9>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 14>",
    "\"abstract\"",
    "\"any\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"goto\"",
    "\"if\"",
    "\"if#\"",
    "\"implements\"",
    "\"import\"",
    "\"int\"",
    "\"interface\"",
    "\"metatype\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"with\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"view\"",
    "\"while\"",
    "\"->\"",
    "\"fun\"",
    "\"...\"",
    "\"rule\"",
    "\"$cut\"",
    "\"$cast\"",
    "\"$reinterp\"",
    "\"alias\"",
    "\"operator\"",
    "\"typedef\"",
    "\"enum\"",
    "\"require\"",
    "\"ensure\"",
    "\"invariant\"",
    "\"@interface\"",
    "\"@singleton\"",
    "\"@forward\"",
    "\"@unerasable\"",
    "\"@virtual\"",
    "\"@packed\"",
    "\"@macro\"",
    "\"@static\"",
    "\"@abstract\"",
    "\"@final\"",
    "\"@native\"",
    "\"@synchronized\"",
    "\"@transient\"",
    "\"@volatile\"",
    "\"@throws\"",
    "\"@access\"",
    "\"@public\"",
    "\"public\"",
    "\"@protected\"",
    "\"protected\"",
    "\"@private\"",
    "\"private\"",
    "<READ_ONLY>",
    "<WRITE_ONLY>",
    "\"rw\"",
    "<NO_READ_WRITE>",
    "\",\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"pragma\"",
    "\"enable\"",
    "\"disable\"",
    "<INTEGER_LITERAL>",
    "<LONG_INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DOUBLE_POINT_LITERAL>",
    "<EXPONENT>",
    "<REPARSE_EXPRESSION>",
    "<REPARSE_STATEMENT>",
    "<REPARSE_TYPE>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<ID_STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"?\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\":=\"",
    "\"!\"",
    "\"~\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"?=\"",
    "\"@=\"",
    "\"@\"",
    "\"#\"",
    "<OPERATOR_LRBRACKETS>",
    "\"\\u2264\"",
    "\"\\u2265\"",
    "<OPERATOR>",
  };

}
