/* Generated By:JavaCC: Do not edit this line. ParseError.java Version 0.7pre1 */
package kiev.parser;

import syntax kiev.Syntax;

public class ParseError extends Exception {
   public ParseError() {
   }
   public ParseError(String message) {
      super(message);
   }
}
