package kiev.fmt.common;

import java.io.ObjectStreamException;

import kiev.vtree.ASTNode;
import kiev.vtree.INode;

public final class Draw_CalcOptionIsHidden extends Draw_CalcOption {
	private static final long serialVersionUID = -314159579454447033L;
	public String							name;

	public boolean calc(INode node) {
		if (node == null)
			return false;
		Object val = node;
		if (!(name == null || name == "" || name == "this"))
			val = node.getVal(node.getAttrSlot(name));
		if (!(val instanceof ASTNode))
			return false;
		return ((ASTNode)val).isAutoGenerated();
	}
	Object readResolve() throws ObjectStreamException {
		if (this.name != null) this.name = this.name.intern();
		return this;
	}
}
