/*******************************************************************************
 * Copyright (c) 2005-2007 UAB "MAKSINETA".
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Common Public License Version 1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/cpl-v10.html
 *
 * Contributors:
 *     "Maxim Kizub" mkizub@symade.com - initial design and implementation
 *******************************************************************************/
package kiev.fmt;
import syntax kiev.Syntax;

import java.io.*;

public final class SyntaxManager {
	private static Hashtable<String,Draw_ATextSyntax>		languageSyntaxMap			= new Hashtable<String,Draw_ATextSyntax>();
	private static Hashtable<Language,Draw_ATextSyntax>	languageEditorSyntaxMap		= new Hashtable<Language,Draw_ATextSyntax>();
	private static Hashtable<Language,Draw_ATextSyntax>	languageInfoSyntaxMap		= new Hashtable<Language,Draw_ATextSyntax>();
	
	private SyntaxManager() {}

	public static Draw_ATextSyntax getDefaultEditorSyntax(Language lng) {
		Draw_ATextSyntax stx = languageEditorSyntaxMap.get(lng);
		if (stx != null)
			return stx;
		stx = getLanguageSyntax(lng.getDefaultEditorSyntax(),false);
		languageEditorSyntaxMap.put(lng, stx);
		return stx;
	}
	
	public static Draw_ATextSyntax getDefaultInfoSyntax(Language lng) {
		Draw_ATextSyntax stx = languageInfoSyntaxMap.get(lng);
		if (stx != null)
			return stx;
		stx = getLanguageSyntax(lng.getDefaultInfoSyntax(),false);
		languageInfoSyntaxMap.put(lng, stx);
		return stx;
	}
	
	public static Draw_ATextSyntax getLanguageSyntax(String name, boolean in_project) {
		trace(Kiev.verbose, "getLanguageSyntax name="+name+" in_project="+in_project);
		if (in_project) {
			DNode ts = Env.getRoot().resolveGlobalDNode(name);
			if (ts instanceof ATextSyntax){
				trace(Kiev.verbose, "getLanguageSyntax ts="+ ts);
				return ts.getCompiled().init();
			}
		}
		Draw_ATextSyntax stx = languageSyntaxMap.get(name);
		if (stx != null)
			return stx;
		return loadLanguageSyntax(name);
	}
	
	public static Draw_ATextSyntax loadLanguageSyntax(String name) {
		Draw_ATextSyntax dts = null;
		InputStream inp = null;
		try {
			inp = Env.class.getClassLoader().getSystemResourceAsStream(name.replace('·','/')+".ser");
			ObjectInput oi = new ObjectInputStream(inp);
			dts = (Draw_ATextSyntax)oi.readObject();
			dts.init();
		} catch (IOException e) {
			System.out.println("Read error while syntax deserialization: "+e);
		} finally {
			if (inp != null)
				inp.close();
		}
		if (dts != null)
			languageSyntaxMap.put(name, dts);
		return dts;
	}

	public static void dumpTextFile(ASTNode node, File f, Draw_ATextSyntax stx)
		throws IOException
	{
		StringBuffer sb = new StringBuffer(1024);
		TextFormatter tf = new TextFormatter();
		tf.setHintEscapes(true);
		if (stx instanceof Draw_XmlDumpSyntax)
			tf.setShowAutoGenerated(true);
		tf.format(node, null, stx);
		Drawable dr = tf.getRootDrawable();
		TextPrinter pr = new TextPrinter(sb);
		pr.draw(dr);
		make_output_dir(f);
		FileOutputStream out = new FileOutputStream(f);
		if (stx instanceof Draw_XmlDumpSyntax) {
			out.write("<?xml version='1.1' encoding='UTF-8' standalone='yes'?>\n".getBytes("UTF-8"));
			out.write("<!--\n".getBytes("UTF-8"));
			out.write(" Copyright (c) 2005-2007 UAB \"MAKSINETA\".\n".getBytes("UTF-8"));
			out.write(" All rights reserved. This program and the accompanying materials\n".getBytes("UTF-8"));
			out.write(" are made available under the terms of the Common Public License Version 1.0\n".getBytes("UTF-8"));
			out.write(" which accompanies this distribution, and is available at\n".getBytes("UTF-8"));
			out.write(" http://www.eclipse.org/legal/cpl-v10.html\n".getBytes("UTF-8"));
			out.write(" \n".getBytes("UTF-8"));
			out.write(" Contributors:\n".getBytes("UTF-8"));
			out.write("     \"Maxim Kizub\" mkizub@symade.com - initial design and implementation\n".getBytes("UTF-8"));
			out.write("-->\n".getBytes("UTF-8"));
		}
		out.write(sb.toString().getBytes("UTF-8"));
		out.close();
	}

	private static void make_output_dir(File f) throws IOException {
		File dir = f.getParentFile();
		if (dir != null) {
			dir.mkdirs();
			if( !dir.exists() || !dir.isDirectory() ) throw new IOException("Can't create output dir "+dir);
		}
	}
	
}
