/* Generated By:JJTree: Do not edit this line. ASTComplexRegularExpressionUnit.java */

package kiev.parser;

public class ASTComplexRegularExpressionUnit extends SimpleNode {

	public int		kind;
	public KString	value;

	public ASTComplexRegularExpressionUnit(int id) {
		super(0);
	}

	public void set(Token t) {
		kind = t.kind;
		value = KString.from(t.image);
	}
}
