/* Generated By:JJTree: Do not edit this line. ASTComplexRegularExpressionUnits.java */

package kiev.parser;

public class ASTComplexRegularExpressionUnits extends SimpleNode {
	public ASTComplexRegularExpressionUnits(int id) {
		super(0);
	}
}
