/* Generated By:JJTree: Do not edit this line. ASTCharacterList.java */

package kiev.parser;

public class ASTCharacterList extends SimpleNode {

	public boolean	not;

	public ASTCharacterList(int id) {
		super(0);
	}

	public void setNot() {
		not = true;
	}

}
