/* Generated By:JJTree: Do not edit this line. ASTLocalLookahead.java */

package kiev.parser;

public class ASTLocalLookahead extends SimpleNode {
	public ASTLocalLookahead(int id) {
		super(0);
	}
}
