/* Generated By:JJTree: Do not edit this line. ASTOptionBinding.java */

package kiev.parser;

public class ASTOptionBinding extends SimpleNode {

	public KString	name;
	public ASTNode	value;

	public ASTOptionBinding(int id) {
		super(0);
	}
	
	public void set(Token t) {
		pos = t.getPos();
		name = KString.from(t.image);
	}

	public void jjtAddChild(ASTNode n, int i) {
		value = n;
	}
}
