/* Generated By:JJTree: Do not edit this line. ASTRegularExpressionSpec.java */

package kiev.parser;

public class ASTRegularExpressionSpec extends SimpleNode {
	public ASTRegularExpressionSpec(int id) {
		super(0);
	}
}
